### ISSUE TITLE
Precision is incorrect for quote

### ISSUE THREAD

**Issue by djkazic** [fuji-money/tdex-app#1]
JSON for `preview` endpoint:
```
{
    "previews": [
        {
            "price": {
                "basePrice": 0.00003415067276825353,
                "quotePrice": 29282
            },
            "fee": {
                "percentageFee": {
                    "baseAsset": "40",
                    "quoteAsset": "40"
                },
                "fixedFee": {
                    "baseAsset": "300",
                    "quoteAsset": "1"
                }
            },
            "amount": "122",
            "asset": "0dea022a8a25abb128b42b0f8e98532bc8bd74f8a77dc81251afcc13168acef7",
            "feeAmount": "1",
            "feeAsset": "0dea022a8a25abb128b42b0f8e98532bc8bd74f8a77dc81251afcc13168acef7"
        }
    ]
}
```

![image](https://github.com/fuji-money/tdex-app/assets/3331929/9de13239-4d0c-487a-bc55-d28a6a1bba4a)
![image](https://github.com/fuji-money/tdex-app/assets/3331929/9a120d46-c03a-4dfa-a8bf-cf625c634641)

**Comment by bordalix** [comment]
@tiero fixed on https://github.com/bordalix/dex.nextjs, you can sync the repo now

Tested on https://dex-nextjs-iota.vercel.app/ 👇 

![Screenshot 2023-09-14 at 17 27 02](https://github.com/fuji-money/tdex-app/assets/9318412/d36b3590-eb17-4699-9fb5-5807e81fdbec)
